# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "gpt-4o"  # or gpt-3.5-turbo-0125 gpt-4o-mini-2024-07-18 gpt-4-turbo https://platform.openai.com/docs/models#current-model-aliases
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "sk-proj-"